AWSTemplateFormatVersion: 2010-09-09
Description: Master stack which creates all required nested stacks

Parameters:
  TemplatePath:
    Type: String
    Description: S3 Bucket Path where the templates are stored
  Environment:
    Type: String
    Description: Select the appropriate environment
    AllowedValues:
      - dev
      - test
      - uat
      - prod
Resources:
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub: "https://s3.amazonaws.com/${TemplatePath}/vpc-stack.yml"
      Tags:
        - Key: Name
          Value: VPCStack
        - Key: Environment
          Value: !Ref Environment
  SecurityStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: 
      - VPCStack
    Properties:
      TemplateURL:
        Fn::Sub: "https://s3.amazonaws.com/${TemplatePath}/security-stack.yml"
      Parameters:
        VPCID: !Ref MyVPC
      Tags:
        - Key: Name
          Value: SecurityStack
        - Key: Environment
          Value: !Ref Environment
      